name: Deploy to Two Windows Servers via SSH (Password)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Windows Host 1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_HOST_1 }}
          username: ${{ secrets.WINDOWS_USERNAME }}
          password: ${{ secrets.WINDOWS_PASSWORD }}
          port: 22
          script: |
            cd C:\inetpub\wwwroot
            git pull https://github.com/hozfia/website.git

      - name: Deploy to Windows Host 2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.WINDOWS_HOST_2 }}
          username: ${{ secrets.WINDOWS_USERNAME }}
          password: ${{ secrets.WINDOWS_PASSWORD }}
          port: 22
          script: |
            cd C:\inetpub\wwwroot
            git pull https://github.com/hozfia/website.git